### PR TITLE
Fix for preact-cli-3

### PR DESCRIPTION
**Pull request by vorobey**

### CODE REVIEW

**Comment by vorobey** [comment]
@pmcalmeida

**Review by pmcalmeida — APPROVED** [review]

**Comment by GarliqBread** [comment]
When is this getting released?

**Comment by pmcalmeida** [comment]
@Prophetaa Merged and released 1.1.0 :) 
thanks @vorobey

**Comment by GarliqBread** [comment]
Thanks guys ❤️ had this locally fixed for a while but forgot to PR, great job!

**Pull request merged**
